//instalar extensão REST Client visto na semana de empregabilidade
//clicar em "Send Request" para obter o 
//resultado da requisição

###  1 - Buscar todos os países
Get http://localhost:3003/countries
Content-Type: application/json

### 2 - Buscar país por id
Get http://localhost:3003/countries/2
Content-Type: application/json

### 3 - Busca com filtros
Get http://localhost:3003/countries/search?name=Bra
Content-Type: application/json

### 4 - Editar país
Post http://localhost:3003/countries/1
Content-Type: application/json

 {
    "name": "Rússia",
    "capital": "Moscou"
 }

### 5 - Deletar país
DELETE http://localhost:3003/countries/1626271643952
Authorization: "12544789542"
Content-Type: application/json

### 6 - Criar país
Post http://localhost:3003/countries
Authorization: "12544789542"
Content-Type: application/json

{
		"name":"Wakanda",
		"capital":"Birnin Zana",
		"continent":"África"
}